import fs from 'node:fs';
import path from 'node:path';
import {
  ensureDir, writeFileAtomic, backupFile, logLine,
} from './util.js';
import { excludeLocally } from './identity.js';
import { renderContext } from './render.js';

/**
 * Automatic context delivery, without depending on any tool's hook output format.
 *
 * Every CLI agent disagrees about what a hook may print. Claude Code injects raw
 * stdout. Gemini CLI requires strict JSON and breaks on a single stray character.
 * Codex wants a `contexts` array. Those formats also move between releases.
 *
 * So hooks here never print anything. Instead they refresh a plain Markdown file
 * that each tool already loads on its own, through the instructions file it
 * reads at startup. Delivery becomes a file write, which no parser can reject
 * and no version bump can break.
 */

export const CONTEXT_FILENAME = path.join('.wingman', 'CONTEXT.md');
export const POINTER_START = '<!-- wingman:context:start -->';
export const POINTER_END = '<!-- wingman:context:end -->';

export function contextFilePath(projectRoot) {
  return path.join(projectRoot, CONTEXT_FILENAME);
}

/**
 * Regenerate the file the agents read. Returns false when there is nothing to
 * say, in which case the file is emptied rather than left stale — a stale
 * context is worse than none, because the agent trusts it.
 */
export function refreshContextFile(project, opts = {}) {
  if (!project?.root || !project?.id) return false;
  const file = contextFilePath(project.root);
  try {
    const rendered = renderContext(project, {
      recent: opts.recent ?? 6,
      maxChars: opts.maxChars ?? 16000,
    });

    if (rendered.empty) {
      if (fs.existsSync(file)) writeFileAtomic(file, EMPTY_NOTE);
      return false;
    }

    const header = [
      '<!-- Generated by Wingman. Do not edit: rewritten on every session. -->',
      `<!-- Last refresh: ${new Date().toISOString()} -->`,
      '',
    ].join('\n');

    ensureDir(path.dirname(file));
    writeFileAtomic(file, header + rendered.text);
    try { fs.chmodSync(file, 0o600); } catch { /* windows */ }
    return true;
  } catch (err) {
    logLine('context-file', err.stack || err.message);
    return false;
  }
}

const EMPTY_NOTE = `<!-- Generated by Wingman -->

No saved context for this project yet. Start work normally.
`;

/**
 * Instruction files each agent loads by itself, relative to the project root.
 * Claude Code and Gemini CLI expand \`@path\` imports inline; Codex and Cursor
 * read the pointer as an instruction, which their agents follow reliably.
 */
export const POINTER_TARGETS = [
  { file: 'CLAUDE.md', agent: 'claude-code', supportsImport: true },
  { file: 'AGENTS.md', agent: 'codex', supportsImport: false },
  { file: 'GEMINI.md', agent: 'gemini-cli', supportsImport: true },
];

function pointerBlock(supportsImport) {
  const posix = CONTEXT_FILENAME.split(path.sep).join('/');
  const body = supportsImport
    ? `## Project context (Wingman)\n\n@${posix}\n`
    : `## Project context (Wingman)\n\nBefore doing anything else, read \`${posix}\`.\n`
      + 'It contains what previous sessions decided, what was already tried and failed,\n'
      + 'and the next concrete step. Treat it as established history: do not redo work\n'
      + 'described there, and do not retry anything listed as a dead end.\n'
      + `If the file is missing or empty, there is no prior context and you can start normally.\n`;
  return `${POINTER_START}\n${body}${POINTER_END}`;
}

/**
 * Add or refresh the pointer inside an instruction file, preserving everything
 * the user or their team already wrote. Idempotent, and takes a backup first.
 */
export function upsertPointer(projectRoot, target) {
  const file = path.join(projectRoot, target.file);
  const block = pointerBlock(target.supportsImport);
  const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';

  if (existing.includes(POINTER_START)) {
    const start = existing.indexOf(POINTER_START);
    const end = existing.indexOf(POINTER_END);
    if (end > start) {
      const next = existing.slice(0, start) + block + existing.slice(end + POINTER_END.length);
      if (next === existing) return { file, changed: false };
      backupFile(file);
      writeFileAtomic(file, next);
      return { file, changed: true, updated: true };
    }
  }

  if (existing) backupFile(file);
  const sep = existing ? (existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n') : '';
  writeFileAtomic(file, existing + sep + block + '\n');
  return { file, changed: true, created: !existing };
}

export function removePointer(projectRoot, target) {
  const file = path.join(projectRoot, target.file);
  if (!fs.existsSync(file)) return { file, changed: false };
  const existing = fs.readFileSync(file, 'utf8');
  const start = existing.indexOf(POINTER_START);
  const end = existing.indexOf(POINTER_END);
  if (start === -1 || end < start) return { file, changed: false };
  backupFile(file);
  const next = (existing.slice(0, start) + existing.slice(end + POINTER_END.length))
    .replace(/\n{3,}/g, '\n\n').trim();
  if (next) writeFileAtomic(file, next + '\n');
  else fs.rmSync(file, { force: true });
  return { file, changed: true };
}

/**
 * Wire up a project so every agent picks the context up on its own.
 * Only writes a pointer for tools actually present, so a Cursor-only user does
 * not get a stray CLAUDE.md committed to their repo.
 */
export function wireProject(project, { agents = [] } = {}) {
  const written = [];
  for (const target of POINTER_TARGETS) {
    if (agents.length && !agents.includes(target.agent)) continue;
    try {
      const res = upsertPointer(project.root, target);
      if (res.changed) written.push(res.file);
    } catch (err) {
      logLine('wire', `${target.file}: ${err.message}`);
    }
  }
  excludeLocally(project.root);
  refreshContextFile(project);
  return written;
}

export function unwireProject(projectRoot) {
  for (const target of POINTER_TARGETS) {
    try { removePointer(projectRoot, target); } catch { /* nothing to remove */ }
  }
  try { fs.rmSync(path.join(projectRoot, CONTEXT_FILENAME), { force: true }); } catch { /* absent */ }
}
